keeg_website:
    resource: "@KEEGWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

oc_forum:
    resource: "@OCForumBundle/Resources/config/routing.yml"
    prefix:      /forum

app:
    resource: @AppBundle/Controller/
    type:      annotation
