
keeg_article_view:
    path:     /articles/{id}
    defaults: { _controller: KEEGArticleBundle:Article:view }
    requirements:
        id:   \d+

keeg_news_view:
    path:     /news/{id}
    defaults: { _controller: KEEGArticleBundle:News:view }
    requirements:
        id:   \d+

keeg_temoignage_view:
    path:     /temoignages/{id}
    defaults: { _controller: KEEGArticleBundle:Temoignage:view }
    requirements:
        id:   \d+

    # Pages de présentation de l'Univers de l'informatique

keeg_universe_iut:
    path:     /IUT_Claude_Bernard_Lyon_1
    defaults: { _controller: KEEGArticleBundle:Universe:iut }

keeg_universe_debouches:
    path:     /metiers
    defaults: { _controller: KEEGArticleBundle:Universe:metier }

keeg_universe_formations:
    path:     /formations
    defaults: { _controller: KEEGArticleBundle:Universe:formation }

keeg_universe_loisirs:
    path:     /loisirs
    defaults: { _controller: KEEGArticleBundle:Universe:loisir }