<?php

namespace KEEG\ArticleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TemoignageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoignageRepository extends EntityRepository
{
}
