# src/OC/PlatformBundle/Resources/config/routing.yml

#general paths :

keeg_website_homepage:
    path:     /
    defaults: { _controller: KEEGWebsiteBundle:Website:index }

keeg_website_iut:
    path:     /IUT
    defaults: { _controller: KEEGArticleBundle:Universe:index }

keeg_website_activities:
    path:     /activities
    defaults: { _controller: KEEGActivityBundle:Activity:index }

keeg_website_forums:
    path:     /forums
    defaults: { _controller: KEEGForumBundle:Forum:index }

keeg_website_news:
    path:     /news
    defaults: { _controller: KEEGArticleBundle:Article:index, section: News }

keeg_website_articles:
    path:     /articles
    defaults: { _controller: KEEGArticleBundle:Article:index, section: Articles }

keeg_website_temoignages:
    path:     /temoignages
    defaults: { _controller: KEEGArticleBundle:Article:index, section: Témoignages }

keeg_website_contact:
    path:     /contact
    defaults: { _controller: KEEGWebsiteBundle:Website:contact }

keeg_website_about:
    path:    /about
    defaults: { _controller: KEEGWebsiteBundle:Website:about }

keeg_website_admin:
    path:    /administration
    defaults: { _controller: KEEGWebsiteBundle:Admin:index }

# Administration specific paths

keeg_admin_projects:
    path:    /administration/projets
    defaults: { _controller: KEEGWebsiteBundle:Project:index }

keeg_admin_projects_view:
    path:    /administration/projets/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:view }
    requirements:
        id:   \d+

keeg_admin_projects_add:
    path:    /administration/projets/add
    defaults: { _controller: KEEGWebsiteBundle:Project:add }

keeg_admin_projects_edit:
    path:    /administration/projets/edit/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:edit }
    requirements:
        id:   \d+

keeg_admin_projects_delete:
    path:    /administration/projets/delete/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:delete }
    requirements:
        id:   \d+

#specific paths (ie. News, Articles, ...) :