# src/OC/PlatformBundle/Resources/config/routing.yml

#general paths :

keeg_website_homepage:
    path:     /
    defaults: { _controller: KEEGWebsiteBundle:Website:index }

keeg_website_iut:
    path:     /IUT
    defaults: { _controller: KEEGArticleBundle:Universe:index }

keeg_website_activities:
    path:     /activities
    defaults: { _controller: KEEGActivityBundle:Activity:index }

keeg_website_forums:
    path:     /forums
    defaults: { _controller: KEEGForumBundle:Forum:index }

keeg_website_news:
    path:     /news
    defaults: { _controller: KEEGArticleBundle:News:index }

keeg_website_articles:
    path:     /articles
    defaults: { _controller: KEEGArticleBundle:Article:index }

keeg_website_temoignages:
    path:     /temoignages
    defaults: { _controller: KEEGArticleBundle:Temoignage:index }

keeg_website_contact:
    path:     /contact
    defaults: { _controller: KEEGWebsiteBundle:Website:contact }

keeg_website_about:
    path:    /about
    defaults: { _controller: KEEGWebsiteBundle:Website:about }

keeg_website_admin:
    path:    /administration
    defaults: { _controller: KEEGWebsiteBundle:Admin:index }

# Administration specific paths

    # Projets

keeg_admin_projects:
    path:    /administration/projets
    defaults: { _controller: KEEGWebsiteBundle:Project:index }

keeg_admin_projects_view:
    path:    /administration/projets/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:view }
    requirements:
        id:   \d+

keeg_admin_projects_add:
    path:    /administration/projets/add
    defaults: { _controller: KEEGWebsiteBundle:Project:add }

keeg_admin_projects_edit:
    path:    /administration/projets/edit/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:edit }
    requirements:
        id:   \d+

keeg_admin_projects_delete:
    path:    /administration/projets/delete/{id}
    defaults: { _controller: KEEGWebsiteBundle:Project:delete }
    requirements:
        id:   \d+

    # Articles

keeg_admin_articles:
    path:    /administration/articles
    defaults: { _controller: KEEGWebsiteBundle:Article:index }

keeg_admin_articles_view:
    path:    /administration/articles/{id}
    defaults: { _controller: KEEGWebsiteBundle:Article:view }
    requirements:
        id:   \d+

keeg_admin_articles_add:
    path:    /administration/articles/add
    defaults: { _controller: KEEGWebsiteBundle:Article:add }

keeg_admin_articles_edit:
    path:    /administration/articles/edit/{id}
    defaults: { _controller: KEEGWebsiteBundle:Article:edit }
    requirements:
        id:   \d+

keeg_admin_articles_delete:
    path:    /administration/articles/delete/{id}
    defaults: { _controller: KEEGWebsiteBundle:Article:delete }
    requirements:
        id:   \d+

    # Temoignages

keeg_admin_temoignages:
    path:    /administration/temoignages
    defaults: { _controller: KEEGWebsiteBundle:Temoignage:index }

keeg_admin_temoignages_view:
    path:    /administration/temoignages/{id}
    defaults: { _controller: KEEGWebsiteBundle:Temoignage:view }
    requirements:
        id:   \d+

keeg_admin_temoignages_add:
    path:    /administration/temoignages/add
    defaults: { _controller: KEEGWebsiteBundle:Temoignage:add }

keeg_admin_temoignages_edit:
    path:    /administration/temoignages/edit/{id}
    defaults: { _controller: KEEGWebsiteBundle:Temoignage:edit }
    requirements:
        id:   \d+

keeg_admin_temoignages_delete:
    path:    /administration/temoignages/delete/{id}
    defaults: { _controller: KEEGWebsiteBundle:Temoignage:delete }
    requirements:
        id:   \d+

    # News

keeg_admin_news:
    path:    /administration/news
    defaults: { _controller: KEEGWebsiteBundle:News:index }

keeg_admin_news_view:
    path:    /administration/news/{id}
    defaults: { _controller: KEEGWebsiteBundle:News:view }
    requirements:
        id:   \d+

keeg_admin_news_add:
    path:    /administration/news/add
    defaults: { _controller: KEEGWebsiteBundle:News:add }

keeg_admin_news_edit:
    path:    /administration/news/edit/{id}
    defaults: { _controller: KEEGWebsiteBundle:News:edit }
    requirements:
        id:   \d+

keeg_admin_news_delete:
    path:    /administration/news/delete/{id}
    defaults: { _controller: KEEGWebsiteBundle:News:delete }
    requirements:
        id:   \d+

#specific paths (ie. News, Articles, ...) :