keeg_activity_projects:
    path:     /projects
    defaults: { _controller: KEEGActivityBundle:Project:index }

keeg_activity_projects_view:
    path:     /projects/{id}
    defaults: { _controller: KEEGActivityBundle:Project:view }
    requirements:
        id:   \d+